/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udcunghoangdao.myframes;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import udcunghoangdao.helper.Data;
import udcunghoangdao.helper.Helper;

/**
 *
 * @author Kitajima2910
 */
public class FRMFunc01 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMFunc01
     */
    public FRMFunc01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnView01 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblICON = new javax.swing.JLabel();
        lblShow01 = new javax.swing.JLabel();
        dateChooser01 = new com.toedter.calendar.JDateChooser();

        btnView01.setText("Xem");
        btnView01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView01ActionPerformed(evt);
            }
        });

        lblICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblShow01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShow01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShow01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblICON, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblShow01, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        dateChooser01.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView01)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dateChooser01, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooser01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnView01)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnView01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView01ActionPerformed
        String data = ((JTextField)dateChooser01.getDateEditor().getUiComponent()).getText();
        
        if(!Helper.isValidDate(data)) {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại định dạng, VD: 29/10/2023", "Hệ Thống", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int zodiac = Helper.checkZodiac(data);
        lblICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + zodiac + ".png")));
        lblShow01.setText("Cung " + Data.getZodiac(zodiac));
    }//GEN-LAST:event_btnView01ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView01;
    private com.toedter.calendar.JDateChooser dateChooser01;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblICON;
    private javax.swing.JLabel lblShow01;
    // End of variables declaration//GEN-END:variables
}
