/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udcunghoangdao.myframes;

import javax.swing.ImageIcon;
import udcunghoangdao.helper.Data;

/**
 *
 * @author Kitajima2910
 */
public class FRMFunc03 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMFunc03
     */
    public FRMFunc03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBeforeICON = new javax.swing.JLabel();
        lblBeforeShow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCurrentICON = new javax.swing.JLabel();
        lblCurrentShow = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAfterICON = new javax.swing.JLabel();
        lblAfterShow = new javax.swing.JLabel();
        cboCHD = new javax.swing.JComboBox<>();

        lblBeforeShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBeforeShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBeforeICON, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBeforeShow, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeforeICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblBeforeShow, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblCurrentShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCurrentShow.setForeground(new java.awt.Color(255, 0, 51));
        lblCurrentShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentICON, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCurrentShow, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCurrentShow, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblAfterShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAfterShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAfterICON, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAfterShow, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAfterICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAfterShow, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        cboCHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cung Bạch Dương", "Cung Kim Ngưu", "Cung Song Tử", "Cung Cự Giải", "Cung Sư Tử", "Cung Xử Nữ", "Cung Thiên Bình", "Cung Thiên Yết", "Cung Nhân Mã", "Cung Ma Kết", "Cung Bảo Bình", "Cung Song Ngư" }));
        cboCHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCHD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cboCHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCHDActionPerformed
        
        int zodiac = cboCHD.getSelectedIndex() + 1;
        
        if(zodiac > 1 && zodiac < 12) {
            
            lblBeforeICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + (zodiac - 1) + ".png")));
            lblBeforeShow.setText("Cung " + Data.getZodiac((zodiac - 1)));
            
            lblCurrentICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + zodiac + ".png")));
            lblCurrentShow.setText("Cung " + Data.getZodiac(zodiac));
            
            lblAfterICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + (zodiac + 1) + ".png")));
            lblAfterShow.setText("Cung " + Data.getZodiac((zodiac + 1)));
        } else if(zodiac == 1) {
            lblBeforeICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + 12 + ".png")));
            lblBeforeShow.setText("Cung " + Data.getZodiac(12));
            
            lblCurrentICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + zodiac + ".png")));
            lblCurrentShow.setText("Cung " + Data.getZodiac(zodiac));
            
            lblAfterICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + 2 + ".png")));
            lblAfterShow.setText("Cung " + Data.getZodiac(2));
        } else if(zodiac == 12) {
            lblBeforeICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + 11 + ".png")));
            lblBeforeShow.setText("Cung " + Data.getZodiac(11));
            
            lblCurrentICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + zodiac + ".png")));
            lblCurrentShow.setText("Cung " + Data.getZodiac(zodiac));
            
            lblAfterICON.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/images/" + 1 + ".png")));
            lblAfterShow.setText("Cung " + Data.getZodiac(1));
        }
        
        
        
    }//GEN-LAST:event_cboCHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCHD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAfterICON;
    private javax.swing.JLabel lblAfterShow;
    private javax.swing.JLabel lblBeforeICON;
    private javax.swing.JLabel lblBeforeShow;
    private javax.swing.JLabel lblCurrentICON;
    private javax.swing.JLabel lblCurrentShow;
    // End of variables declaration//GEN-END:variables
}
