/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestOverloading */

#ifndef _Included_test_TestOverloading
#define _Included_test_TestOverloading
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_TestOverloading
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestOverloading_func__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test_TestOverloading
 * Method:    func
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestOverloading_func__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     test_TestOverloading
 * Method:    func
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestOverloading_func__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
