/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1_Test1 */

#ifndef _Included_test1_Test1
#define _Included_test1_Test1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1_Test1
 * Method:    multiple
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1_Test1_multiple
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     test1_Test1
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1_Test1_sayHi
  (JNIEnv *, jclass);

/*
 * Class:     test1_Test1
 * Method:    sayHiToMe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1_Test1_sayHiToMe
  (JNIEnv *, jclass);

/*
 * Class:     test1_Test1
 * Method:    initLegal
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1_Test1_initLegal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
