/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1_test11_Test2 */

#ifndef _Included_test1_test11_Test2
#define _Included_test1_test11_Test2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1_test11_Test2
 * Method:    times
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1_test11_Test2_times
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
