# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI\ung_dung_ban_ve.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 90, 721, 131))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txtName = QtWidgets.QLineEdit(self.groupBox)
        self.txtName.setGeometry(QtCore.QRect(100, 30, 211, 22))
        self.txtName.setObjectName("txtName")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 55, 16))
        self.label_3.setObjectName("label_3")
        self.cbSex = QtWidgets.QComboBox(self.groupBox)
        self.cbSex.setGeometry(QtCore.QRect(100, 80, 73, 22))
        self.cbSex.setObjectName("cbSex")
        self.cbSex.addItem("")
        self.cbSex.addItem("")
        self.cbSex.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 230, 721, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbkCoffee = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbkCoffee.setGeometry(QtCore.QRect(30, 30, 81, 20))
        self.cbkCoffee.setObjectName("cbkCoffee")
        self.cbkSnack = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbkSnack.setGeometry(QtCore.QRect(290, 30, 61, 20))
        self.cbkSnack.setObjectName("cbkSnack")
        self.spbNumber01 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spbNumber01.setGeometry(QtCore.QRect(100, 90, 42, 22))
        self.spbNumber01.setObjectName("spbNumber01")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_5.setObjectName("label_5")
        self.spbNumber02 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spbNumber02.setGeometry(QtCore.QRect(100, 140, 42, 22))
        self.spbNumber02.setObjectName("spbNumber02")
        self.btnSumSalary = QtWidgets.QPushButton(self.centralwidget)
        self.btnSumSalary.setGeometry(QtCore.QRect(40, 430, 361, 28))
        self.btnSumSalary.setObjectName("btnSumSalary")
        self.txtSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSalary.setGeometry(QtCore.QRect(550, 430, 131, 31))
        self.txtSalary.setObjectName("txtSalary")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 440, 55, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.txtName.textChanged.connect(self.setEnabledForbtnSumSalary)
        self.spbNumber01.textChanged.connect(self.setEnabledForbtnSumSalary)
        self.spbNumber02.textChanged.connect(self.setEnabledForbtnSumSalary)

        self.btnSumSalary.clicked.connect(self.sumSalary)

    def setEnabledForbtnSumSalary(self):
        if len(self.txtName.text()) > 0 and (int(self.spbNumber01.text()) > 0 or int(self.spbNumber02.text()) > 0):
            self.btnSumSalary.setEnabled(True)
        else:
            self.btnSumSalary.setEnabled(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ỨNG DỤNG BÁN VÉ"))
        self.label.setText(_translate("MainWindow", "ỨNG DỤNG BÁN VÉ"))
        self.groupBox.setTitle(_translate("MainWindow", "THÔNG TIN KHÁCH HÀNG"))
        self.label_2.setText(_translate("MainWindow", "Họ & Tên:"))
        self.label_3.setText(_translate("MainWindow", "Giới tính:"))
        self.cbSex.setItemText(0, _translate("MainWindow", "Nam"))
        self.cbSex.setItemText(1, _translate("MainWindow", "Nữ"))
        self.cbSex.setItemText(2, _translate("MainWindow", "Khác"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DỊCH VỤ"))
        self.cbkCoffee.setText(_translate("MainWindow", "Cà Phê"))
        self.cbkSnack.setText(_translate("MainWindow", "Snack"))
        self.label_4.setText(_translate("MainWindow", "Người lớn:"))
        self.label_5.setText(_translate("MainWindow", "Trẻ em:"))
        self.btnSumSalary.setText(_translate("MainWindow", "TÍNH TIỀN"))
        self.label_6.setText(_translate("MainWindow", "VNĐ"))

        self.txtSalary.setReadOnly(True)
        self.btnSumSalary.setEnabled(False)

    def sumSalary(self):
        # print("Họ & Tên: ", self.txtName.text())
        price = {
            "coffe": 100000,
            "snack": 50000,
            "adult": 200000,
            "children": 50000
        }

        salary = 0
        if self.cbkCoffee.checkState() != 0:
            salary += price["coffe"]

        if self.cbkSnack.checkState() != 0:
            salary += price["snack"]

        salary = salary + int(self.spbNumber01.text()) * price["adult"]
        salary = salary + int(self.spbNumber02.text()) * price["children"]

        self.txtSalary.setText(str(salary))

        msg = QtWidgets.QMessageBox()
        msgStr = ""
        msgStr += f"Họ & Tên: {self.txtName.text()}\n"
        msgStr += f"Giới tính: {self.cbSex.currentText()}\n"

        msgCKBArr = []
        if self.cbkCoffee.checkState() != 0:
            msgCKBArr.append(self.cbkCoffee.text())
        if self.cbkSnack.checkState() != 0:
            msgCKBArr.append(self.cbkSnack.text())
        if len(msgCKBArr) > 0:
            msgStr += f"Dịch vụ: {', '.join(msgCKBArr)}\n"
        msgStr += f"Tổng tiền: {salary}"
        msg.setInformativeText(msgStr)
        _translate = QtCore.QCoreApplication.translate
        msg.setWindowTitle(_translate("MainWindow", "CHI TIẾT"))
        msg.exec()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setFixedSize(MainWindow.size())  # Không cho resize
    MainWindow.show()
    sys.exit(app.exec_())
