/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udcunghoangdao;

import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import udcunghoangdao.helper.Helper;
import udcunghoangdao.myframes.FRMFunc01;
import udcunghoangdao.myframes.FRMFunc02;
import udcunghoangdao.myframes.FRMFunc03;

/**
 *
 * @author Kitajima2910
 */
public class Main extends javax.swing.JFrame {

    private FRMFunc01 frm01;
    private FRMFunc02 frm02;
    private FRMFunc03 frm03;

    /**
     * Creates new form Main
     */
    public Main() {
        setResizable(false);
        setTitle("Ứng Dụng Xác Định Cung Hoàng Đạo");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //ImageIcon icon = new ImageIcon(getClass().getResource("images/zodiac.jpg"));
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/images/zodiac.jpg"));
        Image img = icon.getImage();
        desktopMDI = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuDay = new javax.swing.JMenuItem();
        mnuSystem = new javax.swing.JMenuItem();
        mnuAdjacent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMDILayout = new javax.swing.GroupLayout(desktopMDI);
        desktopMDI.setLayout(desktopMDILayout);
        desktopMDILayout.setHorizontalGroup(
            desktopMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        desktopMDILayout.setVerticalGroup(
            desktopMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jMenu3.setText("Chức năng");

        mnuDay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuDay.setText("Xem cung hoàng đạo theo ngày");
        mnuDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDayActionPerformed(evt);
            }
        });
        jMenu3.add(mnuDay);

        mnuSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuSystem.setText("Xem cung hoàng đạo hiện tại");
        mnuSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystemActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSystem);

        mnuAdjacent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuAdjacent.setText("Xem các cung hoàng đạo liền kề");
        mnuAdjacent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdjacentActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAdjacent);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMDI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMDI)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDayActionPerformed
        frm01 = new FRMFunc01();
        Helper.fullScreenJDesktopPane(frm01, desktopMDI);
        frm01.remove(Helper.titlePane(frm01));
        desktopMDI.add(frm01);
        frm01.setVisible(true);
    }//GEN-LAST:event_mnuDayActionPerformed

    private void mnuSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystemActionPerformed
        frm02 = new FRMFunc02();
        Helper.fullScreenJDesktopPane(frm02, desktopMDI);
        frm02.remove(Helper.titlePane(frm02));
        desktopMDI.add(frm02);
        frm02.setVisible(true);
    }//GEN-LAST:event_mnuSystemActionPerformed

    private void mnuAdjacentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdjacentActionPerformed
        frm03 = new FRMFunc03();
        Helper.fullScreenJDesktopPane(frm03, desktopMDI);
        frm03.remove(Helper.titlePane(frm03));
        desktopMDI.add(frm03);
        frm03.setVisible(true);
    }//GEN-LAST:event_mnuAdjacentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMDI;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAdjacent;
    private javax.swing.JMenuItem mnuDay;
    private javax.swing.JMenuItem mnuSystem;
    // End of variables declaration//GEN-END:variables
}
